### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#263]
commit: f1077b4107ea
sometimes there might be an error when start operator controller
```
fatal error: concurrent map writes

goroutine 339 [running]:
runtime.throw(0x2ff20bd, 0x15)
        /Users/zziming/go/go1.14.6/src/runtime/panic.go:1116 +0x72 fp=0xc0005f9990 sp=0xc0005f9960 pc=0x103b062
runtime.mapassign_faststr(0x2d92240, 0xc0001cc390, 0xc0007ce1e0, 0x2c, 0x41fb960)
        /Users/zziming/go/go1.14.6/src/runtime/map_faststr.go:211 +0x529 fp=0xc0005f9a10 sp=0xc0005f9990 pc=0x1018659
sigs.k8s.io/controller-runtime/pkg/webhook.(*Server).Register(0xc000481580, 0xc0007ce1e0, 0x2c, 0x330a680, 0xc000910090)
        /Users/zziming/work/harbor-operator/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go:120 +0x244 fp=0xc0005f9b38 sp=0xc0005f9a10 pc=0x24f4f24
sigs.k8s.io/controller-runtime/pkg/builder.(*WebhookBuilder).registerValidatingWebhook(0xc00050c540)
        /Users/zziming/work/harbor-operator/vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go:127 +0x3bc fp=0xc0005f9c80 sp=0xc0005f9b38 pc=0x262a07c
sigs.k8s.io/controller-runtime/pkg/builder.(*WebhookBuilder).registerWebhooks(0xc00050c540, 0x0, 0x0)
        /Users/zziming/work/harbor-operator/vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go:80 +0x1bf fp=0xc0005f9d50 sp=0xc0005f9c80 pc=0x26296af
sigs.k8s.io/controller-runtime/pkg/builder.(*WebhookBuilder).Complete(0xc00050c540, 0x0, 0x0)
```

**Comment by steven-zou** [comment]
duplicated with #202
